DROP TABLE IF EXISTS BOOK;

CREATE TABLE BOOK (
   id INT AUTO_INCREMENT  PRIMARY KEY,
   isbn VARCHAR(250) NOT NULL,
   title VARCHAR(250) NOT NULL,
   authorName VARCHAR(250) NOT NULL,
   price DECIMAL NOT NULL
);