DROP TABLE IF EXISTS BOOK;

CREATE TABLE CATEGORY (
  id INT AUTO_INCREMENT  PRIMARY KEY,
  name VARCHAR(250) NOT NULL,
);

CREATE TABLE BOOK (
   id INT AUTO_INCREMENT  PRIMARY KEY,
   category_id INT NOT NULL,
   isbn VARCHAR(250) NOT NULL,
   title VARCHAR(250) NOT NULL,
   authorName VARCHAR(250) NOT NULL,
   price DECIMAL NOT NULL,
   FOREIGN KEY (category_id) REFERENCES CATEGORY
);