package com.books.booksstore.book.domain;

import org.assertj.core.api.AbstractObjectAssert;

/**
 * Abstract base class for {@link Book.BookBuilder} specific assertions - Generated by CustomAssertionGenerator.
 */
@javax.annotation.Generated(value="assertj-assertions-generator")
public abstract class AbstractBookBookBuilderAssert<S extends AbstractBookBookBuilderAssert<S, A>, A extends Book.BookBuilder> extends AbstractObjectAssert<S, A> {

  /**
   * Creates a new <code>{@link AbstractBookBookBuilderAssert}</code> to make assertions on actual Book.BookBuilder.
   * @param actual the Book.BookBuilder we want to make assertions on.
   */
  protected AbstractBookBookBuilderAssert(A actual, Class<S> selfType) {
    super(actual, selfType);
  }

}
